apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-cicd
  template:
    metadata:
      labels:
        app: react-cicd
    spec:
      containers:
        - name: react-cicd
          image: itlapav933/react-cicd:latest
          ports:
            - containerPort: 80
