apiVersion: v1
kind: Service
metadata:
  name: react-cicd-service
spec:
  type: NodePort
  selector:
    app: react-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
